### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by fiserjCN** [Warchant/sonar-scanner-action#14]
Hello, I start to get following warning on our github action using this action.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: warchant/setup-sonar-scanner

Hopefully it will be just about increasing the version in action.yml file, right? :)

**Comment by Warchant** [comment]
>Hopefully it will be just about increasing the version in action.yml file, right? :)

Yes: https://github.com/Warchant/setup-sonar-scanner/pull/15
