### ISSUE TITLE
Java 11 is deprecated for SonarCloud (default sonar-scanner version 4.8.0.2856)

### ISSUE THREAD

**Issue by jaseilers** [Warchant/sonar-scanner-action#20]
SonarCloud posts the warning that Java 11 is deprecated and they will stop accepting it soon. Here is the full warning:

```
The version of Java (11.0.17) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)
```

Java 11.0.17 ist the JRE bundled with sonar-scanner 4.8.0.2856. The default for the sonar-scanner should be at least 5.0.0.2966 which is the first version to use Java 17.

**Comment by Warchant** [comment]
Fixed in v6
