### ISSUE TITLE
Github action v6 and sonaqube 9.9

### ISSUE THREAD

**Issue by dzzk** [Warchant/sonar-scanner-action#21]
I am not quietly sure that those problems is related to action version update and not sonarqube version update we have had.
But if there is some additional env parameters we should pass during Warchant action execution - I'll be glad to try it.

I saw a closed issue for ACTIONS_ALLOW_UNSECURE_COMMANDS and transitioning to version 3 as a solution.

Thank you for the action itself and for your answer in advance.

My issue appears next ways:
```
- name: Setup sonarqube
uses: warchant/setup-sonar-scanner@v6
```

```
- name: Run Sonarqube
id: run_sonarqube
run: sonar-scanner
-Dsonar.projectKey=$PROJECT_KEY
-Dsonar.host.url=$HOST_URL
-Dsonar.login=$TOKEN
-Dsonar.javascript.lcov.reportPaths=$GITHUB_WORKSPACE/lcov.info
-Dsonar.test.inclusions=apps/appname/src/**/*.ts,apps/appname/src/**/*.tsx
-Dsonar.test.exclusions=${test_exclusions_args}
-Dsonar.exclusions=${exclusions_args}
```

Which leads to the following issues for SonarQube 9.9.1 (build 69595):

And here is what I see at sonar Scanner Context: appname[Project Analysis]
```
Plugins:
...
Bundled analyzers:
...
Global server settings:
...
Project server settings:
...
Project scanner properties:
- sonar.exclusions=  *FIRST_PROBLEM_HERE, its empty(?)*
- sonar.host.url=XXX (its ok here)
- sonar.javascript.lcov.reportPaths=/lcov.info
- sonar.login=******
- sonar.projectBaseDir=/home/runner/work/appname/appname
- sonar.projectKey=appname
- sonar.scanner.app=ScannerCLI
- sonar.scanner.appVersion=5.0.0.2966
- sonar.sourceEncoding=UTF-8
- sonar.test.exclusions=  *SECOND_PROBLEM_HERE, its empty(?)*
- sonar.test.inclusions=apps/ccm-office/src/**/*.ts,apps/ccm-office/src/**/*.tsx
- sonar.working.directory=/home/runner/work/appname/appname/.scannerwork
```

And from the github workflow run itself:
1. `WARN: Cannot run program "/usr/bin/git" (in directory "/usr/bin"): error=13, Permission denied`
2. `ERROR: Error when running: 'node -v'. Is Node.js available during analysis?`
```
org.sonarsource.nodejs.NodeCommandException: Error when running: 'node -v'. Is Node.js available during analysis?
at org.sonarsource.nodejs.NodeCommand.start(NodeCommand.java:79)
```
_both of those issues comes from /usr/bin and if Iook for $PATH:_
```
/opt/hostedtoolcache/sonar-scanner/5.0.0.2966/x64/sonar-scanner-5.0.0.2966-linux/bin:
/opt/hostedtoolcache/node/16.20.1/x64/bin:
/home/runner/.local/bin:
/opt/pipx_bin:
/home/runner/.cargo/bin:
/home/runner/.config/composer/vendor/bin:
/usr/local/.ghcup/bin:
/home/runner/.dotnet/tools:
/snap/bin:
/usr/local/sbin:
/usr/local/bin:
/usr/sbin:
/usr/bin:
/sbin:
/bin:
/usr/games:
/usr/local/games:
/snap/bin
```
Even if it's ok to run the git or node command from step `run: node -v` or `run: git` is working with no issue, something wrong happening here, and I don't understand

4. `INFO: 2084 files indexed...  (last one was apps/appname/index.js)`
```
INFO: 2206 files indexed
INFO: 25904 files ignored because of inclusion/exclusion patterns
INFO: 89131 files ignored because of scm ignore settings
```

**Comment by Warchant** [comment]
This gh action makes `sonar-scanner` available in PATH.
Once `sonar-scanner` starts, all issues that appear next are `sonar-scanner` issues. 
I recommend to forward this issue to [their repo](https://github.com/SonarSource/sonar-scanner-cli) or to [try another version](https://github.com/SonarSource/sonar-scanner-cli/releases) (default is 5.0.0.2966 for v6).
