### ISSUE TITLE
.Net core 3.1 setup

### ISSUE THREAD

**Issue by victor-ccab** [Warchant/sonar-scanner-action#3]
Could anyone help me with .net core 3.1 setup?

I tried the same workflow that i used with an Angular App but Sonar prompts me **The main branch of this project is empty.**

![image](https://user-images.githubusercontent.com/66277822/90190789-14156200-dd96-11ea-88d3-cbb39817c5dc.png)

I noticed this warning : **WARN: Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.**

I saw at [this post ](https://community.sonarsource.com/t/sonarcloud-github-action-for-net-core-repo-not-detecting-code/22185/3)  that this Action uses the SonarScanner CLI under the hood and i had to use msbuild but I can't figure it out by myself how to do that with github actions...

**My YAML file can be found [here](https://gist.github.com/victor-ccab/5869cceca9b50c691f3ab321979d87c2)**

**Comment by Warchant** [comment]
https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

Official docs say
> **Property missing: `sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.**
>Scanner CLI is not able to analyze .NET projects. Please, use the Scanner for MSBuild. If you are running Scanner for MSBuild, ensure that you are not hitting a known limitation.

You need to install Scanner for [MSBuild](https://github.com/SonarSource/sonar-scanner-msbuild) manually (not using this action).

**Comment by victor-ccab** [comment]
@Warchant Got it! So, basically, there is no way to make It through this github action once It uses SonarScanner CLI, right?

Ok I'll be trying the scanner for msbuild aprouch ... Thank you for your clarifications, helped a lot!! :)
