### ISSUE TITLE
Parameter 'commandLine' cannot be null or empty.

### ISSUE THREAD

**Issue by dansanabria** [Warchant/sonar-scanner-action#7]
Trying to run the workflow below:

```
  name: Check
  on: push
  jobs:
    check:
      name: Action Check
      runs-on: self-hosted
      steps:
        - name: Setup sonarqube
          uses: warchant/setup-sonar-scanner@v3
        - name: Run sonarqube
          run: sonar-scanner -h
```

gives this error:

```
Run warchant/setup-sonar-scanner@v3
  with:
    version: 4.2.0.1873
Error: Action failed with error Error: Parameter 'commandLine' cannot be null or empty.
```

**Comment by Warchant** [comment]
@dansanabria sorry, I can not reproduce. Contribution welcome!

**Comment by swails** [comment]
I know this is late, but I just ran into this problem and traced it back to the environment this was executing in not having access to the `unzip` utility.

Check your self-hosted runner for the availability of `unzip` and install it if it's not present.

A possible workaround is to unzip natively in ts, but that's a lot more work than installing unzip.  Perhaps easier is to simply improve this error message.
