### ISSUE TITLE
The `add-path` command is disabled.

### ISSUE THREAD

**Issue by thanh-nguyen-van** [Warchant/sonar-scanner-action#8]
Today I got this issue: `The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.`

**Comment by alessioerosferri** [comment]
Here, I am getting the same error

**Comment by paulmowat** [comment]
Same here 

Full message below

Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by jose-camallonga** [comment]
I had to add this, not sure if best approach:

```
uses: warchant/setup-sonar-scanner@v1
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
```

**Comment by Warchant** [comment]
Could you try tag [`v3`](https://github.com/Warchant/setup-sonar-scanner/releases/tag/v3)? Is it still an issue?

**Comment by jose-camallonga** [comment]
Looks good for me with v3 👍

**Comment by Warchant** [comment]
Closing then. Solution: update to v3.
