### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by Oladotunn** [Warchant/sonar-scanner-action#9]
Hello, could you kindly help figure out why i get this error?
here's the build link: https://github.com/Nautilus-Technologies/tst/runs/1778519758?check_suite_focus=true

**Comment by Warchant** [comment]
>Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9000

If sonar-scanner cli arg is available in PATH, then this action worked correctly. This is likely your configuration error.
See [configuration example](https://github.com/VeriBlock/alt-integration-cpp/blob/master/sonar-project.properties) for a project.

Also, you may want to update your sonar-maven-plugin: https://stackoverflow.com/questions/45107898/sonarqube-fail-to-get-bootstrap-index-from-server-status-returned-by-url-http
